ci: add action for Definition of Done
equinor/lighthouse-client pull request #1149
Opened 2022-11-29 14:09 UTC by ken-mellem

# Description

This adds a checklist section in the Description which are mandatory in the Definition of Done. See ./dod.yaml. 

The action will fail until all tasks are checked. 

In addition, an action for a valid AB Work Item is added.

Addresses: AB#FILL_IN_YOUR_ISSUE_ID

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] Documentation and comments is added where needed.
- [ ] My code is covered by tests.
- [ ] UX has reviewed relevant UI contributions.

2022-11-29 14:30 UTC, jaysencpp requested changes

2022-11-29 14:30 UTC, jaysencpp commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project
What/where are the style guidelines of this project?

2022-11-29 14:30 UTC, jaysencpp commented on .github/workflows/ab-wi-validation.yml
> +name: ab-story-validation
I don't agree adding this Github Action because not all PRs should require an azure task. It makes creating PRs annoying (e.g. changelog or release PRs).

2022-11-29 15:05 UTC, ken-mellem commented on .github/workflows/ab-wi-validation.yml
> +name: ab-story-validation
Neither the Checklist in the Template nor the AB# ref completed as it stands today. By enforcing two tasks to verify (for now), one at least makes a conscious choice.  The AB WI reference is an indication that code is produced and a nice link to get on the WI. I often go and view the PR - and must locate it when the reference is missing. That is annoying.

I recognize that there are activities that might become cumbersome. For Changelog/Release PR, we must find a workaround that is not too cumbersome, e.g. a label which gets identified and then skips the check - or an always open WI for those activities.

2022-11-29 15:06 UTC, ken-mellem commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project
https://github.com/equinor/lighthouse-client/blob/dev/Contribution.md

2022-11-29 15:16 UTC, ken-mellem commented on .github/workflows/ab-wi-validation.yml
> +name: ab-story-validation
How about a special syntax for branches to ignore, so when you need a PR to update changelog or a specific release PR, use prefix:

```
branches-ignore:
  'release/*' 
```
or
```
branches:
  '!release/*' 
```

2022-11-30 07:54 UTC, jaysencpp commented on .github/workflows/ab-wi-validation.yml
> +name: ab-story-validation
Adding such a workflow where it forces developers to have a related work item on another service for every single GitHub PR will ultimately make developers _not_ want to create more PRs than they actually need to because it's unnecessary workload for the developer. It may sound exaggerating, but it will not result in a good developer experience when a person works on this repository 30hrs/week with the possibility of creating multiple PRs a day.

`I often go and view the PR - and must locate it when the reference is missing. That is annoying.` 
When I go to Azure DevOps and see recently closed user stories by the maintainers of this repository, the majority of them have a PR linked to them. I could understand the frustration if you were to find active user stories and contribute to PRs related to it, but it's not the case here. I don't agree that this is an issue for the project since the maintainers of this repository have linked the majority of recently closed user stories.

`The AB WI reference is an indication that code is produced`
By using the DevOps Board one will get a better indication of the status of a user story. If it's currently in Development/Doing code is being produced, if it's in Development/Done:
* All tasks on the Work item (user story/bug) closed
 * All unit test created and running
 * Code review.
 * Developer tests the PR environment before QA starts testing
* All comments in PR are handled by the developer
 * Approval from Designer
* Approval from Code Review
* Pull request is closed.

If it's in Ready For Test:
* Work Items transferred to Test environment and ready for test.

Opening work items on a separate service for every single PR does not align with how a developer's everyday workflow is. I think the best solution for this is to let the user story's assignee be in charge of when and what is getting linked to. If there are a lack of links on closed work items on DevOps, you could always ask the assigned person to link it.

2022-11-30 08:08 UTC, ken-mellem commented on .github/workflows/ab-wi-validation.yml
> +name: ab-story-validation
I will revert it.

2022-11-30 08:25 UTC, closed without merging

2022-11-30 08:26 UTC, ken-mellem commented
I close this without mergin.
No reason to be disruptive and chang anything so late and so close to the end.